checkoutLocation: '.'
tasks:
  - name: Bootstrap environment
    init: |
      sudo git config --system user.email "trainee@dataminded.be"
      sudo git config --global user.name "Git trainee"
      sudo git config --global init.defaultBranch master
      ./resources/bootstrap.sh
      rm -rf resources